# Generated by Django 2.1.7 on 2019-06-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(max_length=30)),
                ('name_of_dish', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=1000)),
                ('no_of_cals', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(max_length=30)),
                ('calories', models.CharField(max_length=10)),
                ('total_fat', models.CharField(max_length=10)),
                ('saturated_fat', models.CharField(max_length=10)),
                ('sodium', models.CharField(max_length=10)),
                ('total_carbohydrate', models.CharField(max_length=10)),
                ('fiber', models.CharField(max_length=10)),
                ('sugar', models.CharField(max_length=10)),
                ('protein', models.CharField(max_length=10)),
                ('vitamin_a', models.CharField(max_length=10)),
                ('vitamin_c', models.CharField(max_length=10)),
                ('calcium', models.CharField(max_length=10)),
                ('iron', models.CharField(max_length=10)),
            ],
        ),
    ]
